site_name: FluxCEN - Documentation
repo_url: https://github.com/CEN-Nouvelle-Aquitaine/fluxcen
repo_name: CEN-NA/fluxcen
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotate
    - content.code.copy
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue grey
      accent: indigo
      toggle:
        icon: material/toggle-switch-off
        name: Switch to system preference
plugins:
    - search
    #- awesome-pages
markdown_extensions:
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
nav:
  - Accueil:
    - index.md
  - Fonctionnement:
    - fonctionnement.md
  - Utiliser FluxCEN:
    - utiliser_fluxcen.md
  - Exemples:
    - exemples.md
